# Generated by Django 5.2.7 on 2025-10-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_telegramuser_national_id_telegramuser_phone_e164_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
