# Generated by Django 5.2.7 on 2025-10-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_delete_transfer"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="is_registered",
            field=models.BooleanField(default=False),
        ),
    ]
