# Generated by Django 5.2.7 on 2025-10-15 10:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_telegramuser_national_id_telegramuser_phone_e164_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolSnapshot',
            fields=[
                ('at', models.DateTimeField(primary_key=True, serialize=False)),
                ('total_pool', models.BigIntegerField()),
                ('total_principal', models.BigIntegerField()),
                ('acc_interest_per_share', models.DecimalField(decimal_places=18, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='PoolAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.BigIntegerField(default=0)),
                ('accrued_interest', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pool_account', to='users.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='PoolDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('tx_hash', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_deposits', to='users.telegramuser')),
            ],
        ),
        migrations.CreateModel(
            name='PoolWithdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('principal_out', models.BigIntegerField()),
                ('interest_out', models.BigIntegerField(default=0)),
                ('tx_hash', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_withdrawals', to='users.telegramuser')),
            ],
        ),
    ]
