# Generated by Django 5.2.7 on 2025-10-15 10:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_telegramuser_national_id_telegramuser_phone_e164_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('min_score', models.PositiveIntegerField()),
                ('max_score', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrustScoreSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trust_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('risk_category', models.CharField(db_index=True, max_length=32)),
                ('factors', models.JSONField(blank=True, default=dict)),
                ('explanation', models.TextField(blank=True, default='')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_snapshots', to='users.telegramuser')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'calculated_at'], name='scoring_tru_user_id_345282_idx')],
            },
        ),
    ]
