services:
  web:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    image: fse-xrpl-bot:dev
    env_file:
      - ../.env
      - ./env/dev.db.env
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    depends_on:
      - db

  db:
    image: postgres:16
    env_file:
      - ./env/dev.db.env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
