# compose/docker-compose.dev.yml
services:
  web:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    image: fse-xrpl-bot:dev
    env_file:
      - ../.env
      - ./env/dev.db.env
    environment:
      # Ensure Django hits the containerized DB
      DB_HOST: db
      DB_PORT: "5432"
      DJANGO_SETTINGS_MODULE: backend.settings.base
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery_worker:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    image: fse-xrpl-bot:dev
    command: celery -A backend worker -l info --concurrency=4
    env_file:
      - ../.env
      - ./env/dev.db.env
    environment:
      # Ensure Celery reaches Redis & DB (Django reads these in settings)
      DB_HOST: db
      DB_PORT: "5432"
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - ../:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:16
    env_file:
      - ./env/dev.db.env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      # Escape $ with $$ for docker-compose to pass through env vars
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1 -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
