services:
  web:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    image: fse-xrpl-bot:dev
    env_file:
      - ../.env
      - ./env/dev.db.env
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    depends_on:
      - db
      - redis

  celery_worker:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    image: fse-xrpl-bot:dev
    command: celery -A bot_backend worker -l info --concurrency=4
    env_file:
      - ../.env
      - ./env/dev.db.env
    volumes:
      - ../:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    env_file:
      - ./env/dev.db.env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
