# Generated by Django 5.2.7 on 2025-10-15 10:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_telegramuser_national_id_telegramuser_phone_e164_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="absa", max_length=32)),
                ("external_account_id_enc", models.BinaryField()),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("currency", models.CharField(default="ZAR", max_length=8)),
                (
                    "last_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="users.telegramuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("posted_at", models.DateTimeField(db_index=True)),
                ("description", models.TextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("tx_type", models.CharField(db_index=True, max_length=16)),
                (
                    "category",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="banking.bankaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Consent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("permissions", models.JSONField(blank=True, default=list)),
                ("granted_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="users.telegramuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OAuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(db_index=True, default="absa", max_length=32),
                ),
                ("access_token_enc", models.BinaryField()),
                ("refresh_token_enc", models.BinaryField()),
                ("scope", models.CharField(blank=True, default="", max_length=255)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_oauth",
                        to="users.telegramuser",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(
                fields=["user", "provider"], name="banking_ban_user_id_2c0d4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="banktransaction",
            index=models.Index(
                fields=["account", "posted_at"], name="banking_ban_account_69c1e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="banktransaction",
            index=models.Index(
                fields=["category"], name="banking_ban_categor_c9a2f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consent",
            index=models.Index(
                fields=["user", "status"], name="banking_con_user_id_8ffc92_idx"
            ),
        ),
    ]
